name: Rcon Action

on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes
  workflow_dispatch: # This enables manual triggering
    inputs:
      reason:
        description: "Reason for manual run"
        required: false
        default: "Manual trigger"
  repository_dispatch:
    types: [rcon_webhook]

jobs:
  run-action:
    name: Run action.js regularly
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # You can adjust this to your preferred Node.js version

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Install dependencies
        run: npm i # This assumes you have a package.json file
        # If you don't have a package.json, you might use: npm install

      - name: Run action.js
        env:
          RCON_HOST: ${{ secrets.RCON_HOST }}
          RCON_PORT: ${{ secrets.RCON_PORT }}
          RCON_PASSWORD: ${{ secrets.RCON_PASSWORD }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
          CACHE_FILE_PATH: ${{ secrets.CACHE_FILE_PATH }}
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        run: node action.mjs
